syntax = "proto3";

option java_package = "com.bluedragonmc.api.grpc";

enum MapFormat {
  ANVIL = 0;
  POLAR = 1;
}

message MapSource {
  string map_id = 1;
  string map_url = 2;
  MapFormat map_format = 3;
  string map_config = 4;
}

message GameType {
  string name = 1; // The name of the game, e.g. WackyMaze or FastFall
  optional string mode = 3; // The name of the mode

  optional string map_id = 5;
}

enum EnumGameState {
  INITIALIZING = 0;
  STARTING = 1;
  WAITING = 2;
  INGAME = 3;
  ENDING = 4;
  SHUTDOWN = 5;
  UNKNOWN = 6;
  ERROR = 7;
}

message GameState {
  EnumGameState game_state = 1;
  uint32 open_slots = 2;
  bool joinable = 3;
  uint32 max_slots = 4;
}